'use strict';

function printHelp() {
    console.log([
        '',
        'Usage: yamlink [command] [options]',
        '',
        '  yamlink                         Launch Conduit (starts server automatically if needed)',
        '',
        'Commands:',
        '  build                   Index vault and report broken links / duplicate IDs (CI-safe: exits 1 on issues)',
        '  briefing                Vault pulse, tasks due today/overdue, recent activity',
        '  ls                      List notes with unix-style filtering and sorting',
        '  cat <id>                Print a note frontmatter snapshot and body (--at <date> for a historical snapshot)',
        '  grep <text>             Search frontmatter values for matching text',
        '  find                    Structural note search by present/missing fields',
        '  create <type>           Create a new note with optional --field pairs',
        '  diff <id1> <id2>        Compare frontmatter fields between two notes, or use --since for recent changes',
        '  story --since <date>    Vault growth story — then vs now, using the Time Engine (--quarterly for a calendar-quarter review)',
        '  snapshot                Capture an on-demand Time Engine snapshot of the current vault',
        '  restore <timestamp>     Preview or export a reconstructed vault state (read-only unless --output is passed)',
        '  doctor                  Comprehensive vault health and integrity pass',
        '  init [path]             Initialize a new Yamlink vault',
        '  rename <old-id> <new-id> Rename a note id and rewrite wikilinks vault-wide',
        '  search <query>          Search notes by id, name, title, or type',
        '  status                  Fast vault snapshot for scripts and health checks',
        '  health                  Vault health overview — lifecycle, drift, type distribution',
        '  mutations               Browse vault mutation history',
        '  session                 Summarize recent or explicit mutation sessions',
        '  trends                  Vault projections — growth, stale, structure, and forecast',
        '  on <event>              Watch vault and exec a script on matching mutation events (--daemon to run detached; --list/--stop <id>/--stop-all to manage daemons)',
        '  hooks                   Manage persistent webhook registrations for yamlink serve',
        '  schema list|check <type> Schema introspection',
        '  validate                Schema conformance check — required fields, dangling relations (exits 1 on failures)',
        '  query "<query>"         Run a Yamlink query and print results',
        '  report <id>             Note report — type, lifecycle, drift, links for a given ID (--at <date> for a historical snapshot)',
        '  links <id>              Inbound and outbound links for a note (--at <date> for outbound-only historical links)',
        '  graph                   Export the vault graph as JSON (--at <date>, or --since/--until/--points for graph history)',
        '  serve                   Start a local HTTP API server for the vault (--lsp for LSP mode)',
        '  watch                   Watch vault for changes and rebuild index on save',
        '  suggest <id>            Intelligence — suggest fields likely missing from a note',
        '  drift                   Intelligence — notes structurally drifting from their type bundle',
        '  stale                   Intelligence — notes in stale lifecycle state',
        '  orphans                 Intelligence — notes with no inbound or outbound links',
        '  pressure                Intelligence — knowledge pressure: load-bearing drafts, stale hubs, orphans',
        '  signature               Intelligence — structural signature: dominant types, field rigidity, hub concentration, growth rate',
        '  workflow-memory         Intelligence — repeated field pairs added together across authoring sessions',
        '  set <id> <field> <value> Set a frontmatter field on a note (use --clear to remove)',
        '  bulk-set                Set, add, or clear one frontmatter field across explicit note ids',
        '  link <id> <field> <to>  Add a wikilink relation field on a note (--append to keep existing)',
        '  template save <id>      Save an existing note as a blank-skeleton template for its type (--force to overwrite)',
        '  glossary --type <a,b>   Alphabetized glossary of every note of the given type(s), with its own definition and backlinks',
        '  block-backlinks <id>    Show notes linking to exact blocks/headings inside a note',
        '  lenses                  Intelligence — vault change lenses over mutation history',
        '  conduit                 Open Yamlink Conduit in the terminal UI',
        '  completions <shell>     Print shell completion script (bash or zsh)',
        '  export                  Export vault notes as JSON/CSV, or one note as standalone HTML',
        '  publish --out <dir>     Build a static, structured payload for a site generator (Astro/Next/Eleventy)',
        '  env                     Export shell variables for the current vault',
        '',
        'Options:',
        '  --vault <path>          Vault path (default: current directory)',
        '  --json                  Output as JSON',
        '  --host <host>           Host for Conduit/API commands (default: 127.0.0.1)',
        '  --port <n>              Port for serve command (default: 3000)',
        '  --limit <n>             Result limit for supported commands',
        '  --check <list>          Validation checks: schema,broken-links,duplicates',
        '  --all                   Run schema check across every schema target',
        '  --dry-run               Preview changes without writing files',
        '  --quiet                 Suppress advisory or non-essential output',
        '  --rename-file           Rename the owning markdown file when it matches the old id',
        '  --format json|csv|html  Output format for export command (default: json)',
        '  --query "<query>"       Query string for export command',
        '  --id <id>               Note id for single-note HTML export',
        '  --output <path>         Write output to file instead of stdout; restore exports to a directory',
        '  --field <key=value>     Field pair for create command (repeatable)',
        '  --sort name|date|type   Sort order for ls command',
        '  --has <field>           Require a field to be present (repeatable)',
        '  --missing <field>       Require a field to be absent (repeatable)',
        '  --only-types <a,b>      Limit graph export to specific note types',
        '  --at <date>             Reconstruct historical state as of a date (cat, report, links, graph)',
        '  --until <date>          End timestamp for graph history',
        '  --points <n>            Number of graph-history checkpoints, max 50',
        '  --interval <7d>         Graph-history spacing: Nm, Nh, Nd, or Nw',
        '  --quarterly             Since the start of the current calendar quarter (story)',
        '  --reason <text>         Reason label for snapshot command',
        '  --type <type>           Type filter for on command',
        '  --daemon                Run "on" detached, surviving this terminal closing (on command)',
        '  --list                  List registered "on" daemons and their live status (on command)',
        '  --stop <id>             Stop one running "on" daemon by id (on command)',
        '  --stop-all              Stop every running "on" daemon (on command)',
        '  --shell bash|zsh|fish   Shell format for env command',
        '  --stream                Stream live NDJSON output where supported',
        '  --type <a,b>            Note type(s) to include as glossary terms (glossary command)',
        '  --no-group-by-type      Glossary: one flat A-Z list instead of a section per type',
        '  --hide-unreferenced     Glossary: omit terms with no inbound links instead of marking them',
        '  --extra-field <name>    Glossary: an extra frontmatter field to show per entry (repeatable)',
        '  --sort-by-references    Glossary: rank terms by inbound link count instead of alphabetically',
        '  --block <block-id>      Block-backlinks: only show backlinks to one exact block id',
        '  --out <dir>             Output directory for publish command (required)',
        '  --mode preview|prod...  Publish: preview includes draft notes, production excludes them (default: production)',
        '  --site-url <url>        Publish: base URL for sitemap.xml/feed.xml (omit to skip generating them)',
        '  --webhook <url>         Publish: POST a small JSON payload to this URL after a successful build',
        '  --force                 Bypass supported safety/cache prompts (rename, publish)',
        '  --help, -h              Show this help',
        '  --version, -v           Print the installed Yamlink version',
        '',
        'Examples:',
        '  yamlink build --vault ~/vault',
        '  yamlink briefing --vault ~/vault',
        '  yamlink ls --type contact --sort name',
        '  yamlink cat johnny-rico',
        '  yamlink grep rough --field unit',
        '  yamlink find --type contact --has status --missing owner',
        '  yamlink create contact --field name="Jane Doe"',
        '  yamlink doctor --json',
        '  yamlink diff johnny-rico carl-jenkins --json',
        '  yamlink diff --since 2026-06-01T00:00:00.000Z',
        '  yamlink story --since 2026-01-01',
        '  yamlink story --since 2026-01-01 --json',
        '  yamlink story --quarterly            # since the start of the current calendar quarter',
        '  yamlink story --quarterly --json',
        '  yamlink trends',
        '  yamlink trends --json',
        '  yamlink snapshot --reason "before import"',
        '  yamlink restore 2026-07-18T12:00:00.000Z',
        '  yamlink restore 2026-07-18T12:00:00.000Z --output ./restore-preview',
        '  yamlink init ~/notes',
        '  yamlink rename old-id new-id --dry-run --rename-file',
        '  yamlink rename old-id new-id --force',
        '  yamlink search "rico" --type contact',
        '  yamlink status --json',
        '  yamlink on note_created --type contact -- ./sync.sh',
        '  yamlink on field_changed --type task -- node ./notify.js',
        '  yamlink on field_changed --daemon -- ./sync.sh   # survives closing this terminal',
        '  yamlink on --list',
        '  yamlink on --stop daemon-20260819010203-a1b2c3',
        '  yamlink on --stop-all',
        '  yamlink hooks add field_changed https://example.com/yamlink --type task',
        '  yamlink hooks list',
        '  yamlink hooks remove hook-20260812010203-a1b2c3',
        '  yamlink health',
        '  yamlink schema list',
        '  yamlink schema check contact',
        '  yamlink schema check --all --json',
        '  yamlink validate',
        '  yamlink query "where type = contact"',
        '  yamlink query "!view contact select id, name, status"',
        '  yamlink report johnny-rico',
        '  yamlink report johnny-rico --at 2026-01-01',
        '  yamlink links johnny-rico --json',
        '  yamlink links johnny-rico --at 2026-01-01',
        '  yamlink cat johnny-rico --at 2026-01-01',
        '  yamlink graph --only-types contact,unit',
        '  yamlink graph --at 2026-01-01',
        '  yamlink graph --since 2026-01-01 --until 2026-03-01 --points 4',
        '  yamlink serve --port 4000',
        '  yamlink serve --lsp --vault ~/notes',
        '  yamlink watch --vault ~/vault',
        '  yamlink                         Launch Conduit (auto-starts server)',
        '  yamlink conduit --port 3000 --host 127.0.0.1',
        '  yamlink completions bash >> ~/.bash_completion',
        '  eval "$(yamlink completions zsh)"',
        '  yamlink export --format csv --output notes.csv',
        '  yamlink export --query "where type = contact" --format json',
        '  yamlink export --id johnny-rico --format html --output johnny-rico.html',
        '  yamlink publish --out ./site-content',
        '  yamlink publish --out ./site-content --mode preview',
        '  yamlink publish --out ./site-content --site-url https://example.com --webhook https://example.com/deploy',
        '  eval "$(yamlink env --shell zsh)"',
        '  yamlink suggest johnny-rico',
        '  yamlink drift --type contact',
        '  yamlink stale --json',
        '  yamlink orphans --type task',
        '  yamlink pressure',
        '  yamlink signature',
        '  yamlink signature --json',
        '  yamlink workflow-memory --type contact',
        '  yamlink workflow-memory --json',
        '  yamlink session',
        '  yamlink lenses --json',
        '  yamlink set johnny-rico rank "Captain"',
        '  yamlink set johnny-rico status --clear',
        '  yamlink bulk-set --ids johnny-rico,carl-jenkins --field status --value active',
        '  yamlink bulk-set --ids johnny-rico,carl-jenkins --field unit --add roughnecks',
        '  yamlink link johnny-rico unit roughnecks',
        '  yamlink link johnny-rico unit roughnecks --append',
        '  yamlink template save johnny-rico',
        '  yamlink template save johnny-rico --force',
        '  yamlink glossary --type faction,location',
        '  yamlink glossary --type faction --hide-unreferenced --json',
        '  yamlink glossary --type faction --sort-by-references',
        '  yamlink block-backlinks johnny-rico',
        '  yamlink block-backlinks johnny-rico --block t1-ab12cd --json',
        '',
    ].join('\n'));
}

module.exports = { printHelp };
